tasks:
  - init: mvn package -Pproduction

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - runem.lit-plugin@1.2.1:llHUlx8TJ6tFKGa1t6dpLQ==
    - vscjava.vscode-java-test@0.27.0:gNh98vNbqtZC6ydHasFxAQ==
    - pivotal.vscode-spring-boot@1.23.0:1iLvjTfznJrV611qRUeOHg==
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod